import type { PagesContext } from '../lib/types'
import { json } from '../lib/validation'

const publicTypes = "('scheduled', 'manual_official')"
const domains = ['Health & Medicine', 'Disaster & Preparedness', 'Science & Technology', 'News & Public Affairs', 'Product Research']
const emptyMonitor = { hasHistory: false, trackingUrls: null, stillRanked: null, droppedFromTop10: null, droppedFromTop20: null, aliveButNoLongerRanked: null, redirectedOrMoved: null, temporarilyUnavailable: null, confirmedDisappeared: null, replacementCandidates: null, unverifiable: null, events: [], timeline: [] }
const empty = { hasObservation: false, panelId: 'en-us-core-v1', panelVersion: null, methodologyVersion: 'en-core-1', searchLang: 'en', country: 'US', resultCount: 20, latestRunId: null, runType: null, isBaseline: false, observedAt: null, score: null, top20Score: null, previousScore: null, completedRuns: 0, analyzedPages: 0, startDate: null, nextObservation: 'Weekly GitHub Actions schedule', metricCoverage: { available: 0, total: 4, missing: ['Persistence'] }, queriesObserved: 0, resultsCollected: 0, uniqueNormalizedUrls: 0, duplicateNormalizedUrls: 0, top20Available: 0, statusCounts: { success: 0, partial: 0, failure: 0 }, domains: domains.map((name) => ({ name, score: null, top20Score: null, pages: 0, observedAt: null })), monitor: emptyMonitor }

const parseMissing = (value: string) => value ? value.split(/[,、]/).map((item) => item.trim()).filter(Boolean) : []

export const onRequestGet = async ({ request, env }: PagesContext) => {
  const requestedPanel = new URL(request.url).searchParams.get('panel') ?? 'en-us-core-v1'
  const panelId = requestedPanel === 'legacy-ja' ? 'legacy-ja' : 'en-us-core-v1'
  if (!env.ENTROPY_DB) return json(empty, 200, { 'Cache-Control': 'public, max-age=60' })
  const typeClause = panelId === 'legacy-ja' ? "('scheduled', 'manual_official', 'verification', 'diagnostic', 'legacy')" : publicTypes
  const latest = await env.ENTROPY_DB.prepare(`SELECT r.id, r.observed_at, r.score, r.analyzed_pages, r.started_at, t.run_type, c.panel_version, c.methodology_version, c.search_lang, c.country, c.result_count, c.top20_score FROM observation_runs r JOIN observation_run_types t ON t.run_id = r.id AND t.panel_id = ?1 AND t.run_type IN ${typeClause} JOIN observation_run_context c ON c.run_id = r.id AND c.panel_id = ?1 AND c.run_status = 'completed' ORDER BY r.observed_at DESC LIMIT 1`).bind(panelId).first<{ id: string; observed_at: string; score: number | null; analyzed_pages: number; started_at: string; run_type: string; panel_version: string; methodology_version: string; search_lang: string; country: string; result_count: number; top20_score: number | null }>()
  if (!latest) return json(panelId === 'en-us-core-v1' ? empty : { ...empty, panelId: 'legacy-ja', searchLang: 'ja', country: 'JP', resultCount: 10, domains: [] }, 200, { 'Cache-Control': 'public, max-age=60' })
  const count = await env.ENTROPY_DB.prepare(`SELECT COUNT(*) AS count, COALESCE(SUM(r.analyzed_pages), 0) AS pages, MIN(r.started_at) AS start_date FROM observation_runs r JOIN observation_run_types t ON t.run_id = r.id AND t.panel_id = ?1 AND t.run_type IN ${typeClause} JOIN observation_run_context c ON c.run_id = r.id AND c.panel_id = ?1 AND c.run_status = 'completed' WHERE EXISTS (SELECT 1 FROM observation_queries q WHERE q.run_id = r.id)`).bind(panelId).first<{ count: number; pages: number; start_date: string | null }>()
  const domainsResult = await env.ENTROPY_DB.prepare('SELECT domain, score, top20_score, analyzed_pages, observed_at FROM observation_domain_scores WHERE run_id = ?1 ORDER BY domain').bind(latest.id).all<{ domain: string; score: number | null; top20_score: number | null; analyzed_pages: number; observed_at: string }>()
  const domainAvailability = await env.ENTROPY_DB.prepare('SELECT domain, SUM(CASE WHEN returned_count >= 11 THEN 1 ELSE 0 END) AS top20_available FROM observation_queries WHERE run_id = ?1 GROUP BY domain').bind(latest.id).all<{ domain: string; top20_available: number }>()
  const domainAvailabilityMap = new Map(domainAvailability.results.map((item) => [item.domain, Number(item.top20_available)]))
  const auditStats = await env.ENTROPY_DB.prepare("SELECT COUNT(*) AS queries, COALESCE(SUM(returned_count), 0) AS results, SUM(CASE WHEN returned_count >= 11 THEN 1 ELSE 0 END) AS top20_available, SUM(CASE WHEN status = 'success' THEN 1 ELSE 0 END) AS success, SUM(CASE WHEN status = 'partial' THEN 1 ELSE 0 END) AS partial, SUM(CASE WHEN status = 'failure' THEN 1 ELSE 0 END) AS failure FROM observation_queries WHERE run_id = ?1").bind(latest.id).first<{ queries: number; results: number; top20_available: number; success: number; partial: number; failure: number }>()
  const uniqueUrls = await env.ENTROPY_DB.prepare('SELECT COUNT(DISTINCT normalized_url) AS count FROM observation_pages WHERE run_id = ?1').bind(latest.id).first<{ count: number }>()
  const duplicateRows = Math.max(0, latest.analyzed_pages - Number(uniqueUrls?.count ?? 0))
  const top20Available = Number(auditStats?.top20_available ?? 0)
  const previous = await env.ENTROPY_DB.prepare(`SELECT r.score FROM observation_runs r JOIN observation_run_types t ON t.run_id = r.id AND t.panel_id = ?1 AND t.run_type IN ${typeClause} JOIN observation_run_context c ON c.run_id = r.id AND c.panel_id = ?1 AND c.run_status = 'completed' WHERE r.observed_at < ?2 ORDER BY r.observed_at DESC LIMIT 1`).bind(panelId, latest.observed_at).first<{ score: number | null }>()
  const queryRows = await env.ENTROPY_DB.prepare('SELECT missing_metrics FROM observation_queries WHERE run_id = ?1').bind(latest.id).all<{ missing_metrics: string }>()
  const missing = [...new Set(queryRows.results.flatMap((row) => parseMissing(row.missing_metrics)))]
  const publicCount = Number(count?.count ?? 0)
  const monitor = await monitorFor({ env, panelId, latestRunId: latest.id, latestObservedAt: latest.observed_at, previousExists: Boolean(previous) })
  return json({ hasObservation: true, panelId, panelVersion: latest.panel_version, methodologyVersion: latest.methodology_version, searchLang: latest.search_lang, country: latest.country, resultCount: latest.result_count, latestRunId: latest.id, runType: latest.run_type, isBaseline: panelId === 'en-us-core-v1' && latest.run_type === 'manual_official' && publicCount === 1, observedAt: latest.observed_at, score: latest.score, top20Score: top20Available > 0 ? latest.top20_score : null, previousScore: previous?.score ?? null, completedRuns: publicCount, analyzedPages: count?.pages ?? 0, startDate: count?.start_date ?? latest.started_at, nextObservation: 'Weekly GitHub Actions schedule', metricCoverage: { available: Math.max(0, 4 - missing.length), total: 4, missing }, queriesObserved: Number(auditStats?.queries ?? 0), resultsCollected: Number(auditStats?.results ?? 0), uniqueNormalizedUrls: Number(uniqueUrls?.count ?? 0), duplicateNormalizedUrls: duplicateRows, top20Available, statusCounts: { success: Number(auditStats?.success ?? 0), partial: Number(auditStats?.partial ?? 0), failure: Number(auditStats?.failure ?? 0) }, domains: domainsResult.results.map((item) => ({ name: item.domain, score: item.score, top20Score: domainAvailabilityMap.get(item.domain) ? item.top20_score : null, pages: item.analyzed_pages, observedAt: item.observed_at })), monitor }, 200, { 'Cache-Control': 'public, max-age=60' })
}

const monitorFor = async ({ env, panelId, latestRunId, latestObservedAt, previousExists }: { env: PagesContext['env']; panelId: string; latestRunId: string; latestObservedAt: string; previousExists: boolean }) => {
  if (!env.ENTROPY_DB || !previousExists) return emptyMonitor
  const tracking = await env.ENTROPY_DB.prepare('SELECT COUNT(DISTINCT normalized_url) AS count FROM observation_pages WHERE run_id = ?1').bind(latestRunId).first<{ count: number }>()
  const departures = await env.ENTROPY_DB.prepare("SELECT search_status, COUNT(*) AS count FROM search_rank_history WHERE panel_id = ?1 AND run_id = ?2 GROUP BY search_status").bind(panelId, latestRunId).all<{ search_status: string; count: number }>()
  const droppedUrls = await env.ENTROPY_DB.prepare("SELECT normalized_url FROM search_rank_history WHERE panel_id = ?1 AND run_id = ?2 AND search_status IN ('dropped_from_top_10','dropped_from_top_20')").bind(panelId, latestRunId).all<{ normalized_url: string }>()
  const latestHistory = await env.ENTROPY_DB.prepare('SELECT normalized_url, result_state FROM url_verification_history WHERE panel_id = ?1 AND observed_at <= ?2 ORDER BY observed_at DESC').bind(panelId, latestObservedAt).all<{ normalized_url: string; result_state: string }>()
  const states = new Map<string, string>()
  for (const row of latestHistory.results) if (!states.has(row.normalized_url)) states.set(row.normalized_url, row.result_state)
  const countState = (state: string) => [...states.values()].filter((item) => item === state).length
  const eventRows = await env.ENTROPY_DB.prepare('SELECT id, normalized_url, title, domain, query, previous_rank, last_seen_at, search_status, web_status, redirect_url, confidence, evidence, first_observed_at FROM disappearance_events WHERE panel_id = ?1 ORDER BY updated_at DESC LIMIT 12').bind(panelId).all<{ id: number; normalized_url: string; title: string | null; domain: string; query: string; previous_rank: number | null; last_seen_at: string; search_status: string; web_status: string; redirect_url: string | null; confidence: string; evidence: string; first_observed_at: string }>()
  const runs = await env.ENTROPY_DB.prepare("SELECT r.id, r.observed_at, c.search_departures, c.web_disappearance_candidates, c.confirmed_disappeared FROM observation_runs r JOIN observation_run_types t ON t.run_id = r.id AND t.panel_id = ?1 AND t.run_type IN ('scheduled','manual_official') JOIN observation_run_context c ON c.run_id = r.id WHERE c.panel_id = ?1 AND c.run_status = 'completed' ORDER BY r.observed_at DESC LIMIT 12").bind(panelId).all<{ id: string; observed_at: string; search_departures: number; web_disappearance_candidates: number; confirmed_disappeared: number }>()
  const departureMap = new Map(departures.results.map((row) => [row.search_status, Number(row.count)]))
  const timeline = runs.results.reverse().map((run) => ({ runId: run.id, observedAt: run.observed_at, trackedUrls: null, searchDepartures: run.search_departures, aliveButNoLongerRanked: null, redirected: null, temporarilyUnavailable: null, confirmedDisappeared: run.confirmed_disappeared }))
  const aliveButNoLongerRanked = droppedUrls.results.filter((row) => ['alive', 'moved', 'redirected'].includes(states.get(row.normalized_url) ?? '')).length
  return { hasHistory: true, trackingUrls: Number(tracking?.count ?? 0), stillRanked: departureMap.get('still_ranked') ?? 0, droppedFromTop10: departureMap.get('dropped_from_top_10') ?? 0, droppedFromTop20: departureMap.get('dropped_from_top_20') ?? 0, aliveButNoLongerRanked, redirectedOrMoved: countState('moved') + countState('redirected'), temporarilyUnavailable: countState('temporarily_unavailable') + countState('persistent_unavailable'), confirmedDisappeared: countState('disappeared'), replacementCandidates: countState('replaced_candidate'), unverifiable: countState('unverifiable') + countState('blocked'), events: eventRows.results.map((event) => ({ ...event, title: event.title ?? 'Untitled page' })), timeline }
}
