import type { PagesContext } from '../../lib/types'
import { json } from '../../lib/validation'

const parseMetrics = (value: string | null) => { try { return value ? JSON.parse(value) : {} } catch { return {} } }
const parseMissing = (value: string) => value ? value.split(/[,、]/).map((item) => item.trim()).filter(Boolean) : []

export const onRequestGet = async ({ request, env }: PagesContext) => {
  const panelId = new URL(request.url).searchParams.get('panel') === 'legacy-ja' ? 'legacy-ja' : 'en-us-core-v1'
  if (!env.ENTROPY_DB) return json({ hasObservation: false, panelId, queries: [] }, 200, { 'Cache-Control': 'public, max-age=60' })
  const typeClause = panelId === 'legacy-ja' ? "('scheduled', 'manual_official', 'verification', 'diagnostic', 'legacy')" : "('scheduled', 'manual_official')"
  const run = await env.ENTROPY_DB.prepare(`SELECT r.id, r.observed_at, r.score, r.analyzed_pages, r.calculation_version, t.run_type, c.methodology_version, c.top20_score FROM observation_runs r JOIN observation_run_types t ON t.run_id = r.id AND t.panel_id = ?1 AND t.run_type IN ${typeClause} JOIN observation_run_context c ON c.run_id = r.id AND c.panel_id = ?1 AND c.run_status = 'completed' ORDER BY r.observed_at DESC LIMIT 1`).bind(panelId).first<{ id: string; observed_at: string; score: number | null; analyzed_pages: number; calculation_version: string; run_type: string; methodology_version: string; top20_score: number | null }>()
  if (!run) return json({ hasObservation: false, panelId, queries: [] }, 200, { 'Cache-Control': 'public, max-age=60' })
  const queries = await env.ENTROPY_DB.prepare('SELECT domain, query, query_id, query_type, requested_count, returned_count, status, score, top20_score, metrics_json, top10_metrics_json, top20_metrics_json, missing_metrics, error_reason, query_rationale FROM observation_queries WHERE run_id = ?1 ORDER BY id').bind(run.id).all<{ domain: string; query: string; query_id: string | null; query_type: string | null; requested_count: number; returned_count: number; status: string; score: number | null; top20_score: number | null; metrics_json: string; top10_metrics_json: string | null; top20_metrics_json: string | null; missing_metrics: string; error_reason: string | null; query_rationale: string | null }>()
  const pages = await env.ENTROPY_DB.prepare('SELECT query_id, query, cluster_id, hostname FROM observation_pages WHERE run_id = ?1 ORDER BY query_id, rank').bind(run.id).all<{ query_id: string | null; query: string; cluster_id: string | null; hostname: string }>()
  const clusters = new Map<string, Map<string, Set<string>>>()
  for (const page of pages.results) { const queryKey = page.query_id ?? page.query; if (!clusters.has(queryKey)) clusters.set(queryKey, new Map()); const byCluster = clusters.get(queryKey)!; const cluster = page.cluster_id ?? 'unclassified'; if (!byCluster.has(cluster)) byCluster.set(cluster, new Set()); byCluster.get(cluster)!.add(page.hostname) }
  const publicRunCount = (await env.ENTROPY_DB.prepare(`SELECT COUNT(*) AS count FROM observation_runs r JOIN observation_run_types t ON t.run_id = r.id AND t.panel_id = ?1 AND t.run_type IN ${typeClause} JOIN observation_run_context c ON c.run_id = r.id AND c.panel_id = ?1 AND c.run_status = 'completed' WHERE EXISTS (SELECT 1 FROM observation_queries q WHERE q.run_id = r.id)`).bind(panelId).first<{ count: number }>())?.count ?? 0
  const previous = await env.ENTROPY_DB.prepare(`SELECT r.score FROM observation_runs r JOIN observation_run_types t ON t.run_id = r.id AND t.panel_id = ?1 AND t.run_type IN ${typeClause} WHERE r.observed_at < ?2 ORDER BY r.observed_at DESC LIMIT 1`).bind(panelId, run.observed_at).first<{ score: number | null }>()
  const duplicate = (await env.ENTROPY_DB.prepare('SELECT COUNT(*) AS count FROM (SELECT normalized_url FROM observation_pages WHERE run_id = ?1 GROUP BY normalized_url HAVING COUNT(*) > 1)').bind(run.id).first<{ count: number }>())?.count ?? 0
  return json({ hasObservation: true, panelId, runId: run.id, runType: run.run_type, isBaseline: panelId === 'en-us-core-v1' && run.run_type === 'manual_official' && publicRunCount === 1, observedAt: run.observed_at, score: run.score, top20Score: run.top20_score, analyzedPages: run.analyzed_pages, methodologyVersion: run.methodology_version, previousScore: previous?.score ?? null, duplicateNormalizedUrls: duplicate, queries: queries.results.map((item) => ({ ...item, metrics: parseMetrics(item.metrics_json), top10Metrics: parseMetrics(item.top10_metrics_json ?? item.metrics_json), top20Metrics: parseMetrics(item.top20_metrics_json), missingMetrics: parseMissing(item.missing_metrics), clusters: [...(clusters.get(item.query_id ?? item.query)?.entries() ?? [])].map(([clusterId, hosts]) => ({ clusterId, pages: hosts.size, hostnames: [...hosts] })) })) }, 200, { 'Cache-Control': 'public, max-age=60' })
}
