import { FormEvent, useEffect, useMemo, useState } from 'react'
import { emptyExperiment, emptyOfficialOverview } from './lib/sample'
import { auditHref, isAuditPath, isKnownPath, localeFromPath, locales, t } from './lib/i18n'
import type { ExperimentResult, Locale, OfficialAudit, OfficialOverview, OfficialQueryAudit } from './lib/types'

const formatDate = (value: string | null | undefined, locale: Locale) => value ? new Intl.DateTimeFormat(locale === 'zh-CN' ? 'zh-CN' : locale, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'
const formatCount = (value: number | null | undefined) => value === null || value === undefined ? '—' : value.toLocaleString()
const homeHref = (locale: Locale) => locale === 'en' ? '/' : `/${locale === 'zh-CN' ? 'zh' : locale}/`
const statusLabel = (status: string, copy: ReturnType<typeof t>) => ({ success: copy.complete, partial: copy.partialStatus, failure: copy.failed, dropped_from_top_10: copy.dropped10, dropped_from_top_20: copy.dropped20, moved: copy.moved, redirected: copy.moved, disappeared: copy.disappeared, replaced_candidate: copy.replacement, temporarily_unavailable: copy.temporary, persistent_unavailable: copy.temporary, blocked: copy.unverifiable, unverifiable: copy.unverifiable }[status] ?? status.replaceAll('_', ' '))
const top20Score = (item: OfficialQueryAudit) => item.returned_count >= 11 ? item.top20_score : null

function Arrow() { return <svg className="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15M13 6l6 6-6 6" /></svg> }
function SearchIcon() { return <svg className="icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.8" cy="10.8" r="6.5" /><path d="m16 16 5 5" /></svg> }
function ClockIcon() { return <svg className="icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8.5" /><path d="M12 7v5l3 2" /></svg> }
function InfoIcon() { return <svg className="icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9" /><path d="M12 10v6M12 7.5h.01" /></svg> }

function ScoreOverview({ official, copy }: { official: OfficialOverview; copy: ReturnType<typeof t> }) {
  const items = [
    { label: copy.score, value: official.score, note: official.hasObservation ? copy.provisional : copy.noObservation, isScore: true },
    { label: copy.queriesObserved, value: official.queriesObserved, note: 'Fixed English panel', isScore: false },
    { label: copy.resultsCollected, value: official.resultsCollected, note: 'Brave search metadata', isScore: false },
    { label: copy.uniqueUrls, value: official.uniqueNormalizedUrls, note: `${official.duplicateNormalizedUrls} ${copy.duplicateUrls.toLowerCase()}`, isScore: false },
  ]
  return <section className="overview-section" id="overview" aria-labelledby="overview-title"><div className="section-heading"><div><p className="section-kicker">01 / OBSERVATION OVERVIEW</p><h2 id="overview-title">Current observation</h2></div><p className="section-context">{copy.context}<br /><span>{official.panelId} · {official.methodologyVersion}</span></p></div><div className="score-grid">{items.map((item) => <article className={`score-card ${item.isScore ? 'score-primary' : 'score-supporting'}`} key={item.label}><span>{item.label}</span><strong>{item.value === null || item.value === undefined ? '—' : formatCount(item.value)}{item.value !== null && item.value !== undefined && item.isScore && <small>/100</small>}</strong><em>{item.note}</em></article>)}</div><div className="score-footnote"><span>{official.isBaseline ? `● ${copy.baseline}` : copy.provisional}</span><span>{official.top20Available > 0 ? `${copy.top20}: ${official.top20Score ?? '—'}/100` : `${copy.top20}: ${copy.top20Unavailable}`}</span></div></section>
}

function BaselineEstablished({ copy }: { copy: ReturnType<typeof t> }) {
  return <section className="baseline-section" id="baseline" aria-labelledby="baseline-title"><div className="baseline-card"><div className="baseline-mark"><ClockIcon /></div><div><p className="section-kicker">02 / FIRST OFFICIAL OBSERVATION</p><h2 id="baseline-title">{copy.baselineTitle}</h2><p>{copy.baselineBody}</p><div className="baseline-rule" /><small>{copy.notEnough}</small></div></div></section>
}

function Monitor({ official, copy }: { official: OfficialOverview; copy: ReturnType<typeof t> }) {
  const monitor = official.monitor
  const cards = [{ label: copy.tracking, value: monitor.trackingUrls }, { label: copy.stillRanked, value: monitor.stillRanked }, { label: copy.dropped10, value: monitor.droppedFromTop10 }, { label: copy.dropped20, value: monitor.droppedFromTop20 }, { label: copy.aliveDropped, value: monitor.aliveButNoLongerRanked }, { label: copy.moved, value: monitor.redirectedOrMoved }, { label: copy.temporary, value: monitor.temporarilyUnavailable }, { label: copy.disappeared, value: monitor.confirmedDisappeared }, { label: copy.replacement, value: monitor.replacementCandidates }, { label: copy.unverifiable, value: monitor.unverifiable }]
  return <section className="monitor-section" id="monitor" aria-labelledby="monitor-title"><div className="section-heading"><div><p className="section-kicker">02 / DISAPPEARANCE MONITOR</p><h2 id="monitor-title">{copy.monitorTitle}</h2></div><p className="section-context">{copy.monitorIntro}</p></div>{!monitor.hasHistory ? <div className="history-empty"><SearchIcon /><strong>{copy.notEnough}</strong><p>{copy.monitorEmpty}</p></div> : <><div className="monitor-grid">{cards.map((card) => <div className="monitor-stat" key={card.label}><span>{card.label}</span><strong>{formatCount(card.value)}</strong></div>)}</div><div className="monitor-split"><div><div className="split-heading"><span>A · SEARCH-RESULT DEPARTURE</span><small>{copy.top10} / {copy.top20}</small></div><p>Pages that remain on the web but leave the observed search results.</p><div className="split-bars"><div><span>{copy.top10}</span><i style={{ width: `${Math.min(100, (monitor.droppedFromTop10 ?? 0) / Math.max(1, monitor.trackingUrls ?? 1) * 100)}%` }} /></div><div><span>{copy.top20}</span><i className="amber" style={{ width: `${Math.min(100, (monitor.droppedFromTop20 ?? 0) / Math.max(1, monitor.trackingUrls ?? 1) * 100)}%` }} /></div></div></div><div><div className="split-heading"><span>B · WEB-PAGE STATUS</span><small>HTTP evidence</small></div><p>Pages checked directly, separately from search ranking.</p><div className="status-dots"><span><i className="dot teal" />{copy.moved}</span><span><i className="dot amber" />{copy.temporary}</span><span><i className="dot red" />{copy.disappeared}</span></div></div></div></>}</section>
}

function Timeline({ official, copy }: { official: OfficialOverview; copy: ReturnType<typeof t> }) {
  return <section className="timeline-section" id="timeline" aria-labelledby="timeline-title"><div className="section-heading"><div><p className="section-kicker">04 / HISTORY</p><h2 id="timeline-title">{copy.timeline}</h2></div><p className="section-context">Counts are published only after an official run completes.</p></div>{!official.monitor.hasHistory ? <div className="timeline-empty"><span>BASELINE</span><strong>{copy.notEnough}</strong><small>Timeline will populate after the next official observation.</small></div> : <div className="timeline-track">{official.monitor.timeline.map((item) => <div className="timeline-node" key={item.runId}><i /><strong>{formatDate(item.observedAt, 'en').split(',')[0]}</strong><span>{item.searchDepartures ?? '—'} departures</span></div>)}</div>}</section>
}

function Categories({ official, copy }: { official: OfficialOverview; copy: ReturnType<typeof t> }) {
  return <section className="category-section" id="categories" aria-labelledby="category-title"><div className="section-heading"><div><p className="section-kicker">03 / PANEL COMPARISON</p><h2 id="category-title">{copy.category}</h2></div><p className="section-context">The primary score uses Top 10. Top 20 is a supporting view.</p></div><div className="category-table-wrap"><table className="category-table"><thead><tr><th>Category</th><th>{copy.top10}</th><th>{copy.top20}</th><th>Pages</th></tr></thead><tbody>{official.domains.map((item) => <tr key={item.name}><th>{item.name}</th><td>{item.score ?? '—'}{item.score !== null && <small>/100</small>}</td><td className={item.top20Score === null ? 'unavailable-cell' : ''}>{item.top20Score === null ? copy.top20Unavailable : item.top20Score}{item.top20Score !== null && <small>/100</small>}</td><td>{formatCount(item.pages)}</td></tr>)}</tbody></table></div></section>
}

function Events({ official, copy }: { official: OfficialOverview; copy: ReturnType<typeof t> }) {
  return <section className="events-section" id="events" aria-labelledby="events-title"><div className="section-heading"><div><p className="section-kicker">05 / EVENT LOG</p><h2 id="events-title">{copy.events}</h2></div><p className="section-context">Search departure is not web disappearance. Each event keeps its evidence.</p></div>{!official.monitor.events.length ? <div className="events-empty"><ClockIcon /><strong>{copy.noEvents}</strong><p>Events will appear when tracked URLs change state.</p></div> : <div className="event-list">{official.monitor.events.map((event) => <article className="event-row" key={event.id}><div className="event-icon"><ClockIcon /></div><div className="event-main"><strong>{event.title}</strong><span>{event.domain} · {event.query}</span><p>{event.evidence}</p></div><div className="event-meta"><b>{statusLabel(event.search_status, copy)}</b><span>{statusLabel(event.web_status, copy)}</span><small>{formatDate(event.updated_at ?? event.last_seen_at, 'en')}</small></div></article>)}</div>}</section>
}

function LiveSearch({ locale, copy }: { locale: Locale; copy: ReturnType<typeof t> }) {
  const [query, setQuery] = useState('')
  const [result, setResult] = useState<ExperimentResult>(emptyExperiment)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [shared, setShared] = useState(false)
  const run = async (event: FormEvent) => { event.preventDefault(); const normalized = query.trim().replace(/\s+/g, ' '); if (normalized.length < 2 || normalized.length > 80 || /https?:\/\//i.test(normalized) || /@/.test(normalized)) { setError(copy.error); return }; setError(''); setBusy(true); try { const response = await fetch(`/api/live?q=${encodeURIComponent(normalized)}&lang=${encodeURIComponent(locale)}`, { headers: { Accept: 'application/json' } }); const payload = await response.json(); if (!response.ok && !payload.result) throw new Error('unavailable'); setResult(payload.result ?? payload); if (!response.ok) setError(payload.error ?? copy.noMeasured) } catch { setResult(emptyExperiment(normalized)); setError(copy.noMeasured) } finally { setBusy(false) } }
  const share = async () => { const text = result.totalResults ? `${copy.top10Sentence(result.highSimilarityPairs, Math.min(10, result.totalResults))} ${copy.lineageSentence(result.lineageCount)} ${copy.primarySentence(result.primarySourceReach)}` : copy.noMeasured; try { await navigator.clipboard.writeText(`${text}\n${window.location.href}#live`); await fetch('/api/live/usage', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ event: 'share', lang: locale }) }); setShared(true) } catch { setShared(false) } }
  return <section className="live-section" id="live" aria-labelledby="live-title"><div className="section-heading"><div><p className="section-kicker">06 / ONE-QUERY LIVE SEARCH</p><h2 id="live-title">{copy.liveTitle}</h2></div><p className="section-context">{copy.liveIntro}<br />{copy.liveNote}</p></div><form className="live-form" onSubmit={run}><label htmlFor="live-query">{copy.searchPlaceholder}</label><div><input id="live-query" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={copy.searchPlaceholder} maxLength={80} /><button type="submit" disabled={busy}>{busy ? copy.searching : copy.search} <Arrow /></button></div>{error && <p className="form-error" role="alert"><InfoIcon />{error}</p>}</form>{result.totalResults > 0 && <div className="live-result"><div className="live-summary"><p>{copy.top10Sentence(result.highSimilarityPairs, Math.min(10, result.totalResults))}</p><p>{copy.lineageSentence(result.lineageCount)}</p><p>{copy.primarySentence(result.primarySourceReach)}</p></div><div className="live-metrics"><div><span>{copy.results}</span><strong>{result.totalResults}</strong></div><div><span>{copy.lineages}</span><strong>{result.lineageCount}</strong></div><div><span>{copy.primary}</span><strong>{result.primarySourceReach}</strong></div><div><span>{copy.unavailable}</span><strong>{result.unavailableCount}</strong></div></div><div className="lineage-bars">{result.clusters.map((cluster) => <div key={cluster.id}><span>{cluster.label}</span><i style={{ width: `${cluster.resultCount / Math.max(1, result.totalResults) * 100}%`, background: cluster.color }} /><small>{cluster.resultCount}</small></div>)}</div><button className="share-button" type="button" onClick={share}>{shared ? copy.shared : copy.share} <Arrow /></button></div>}</section>
}

function Methodology({ copy }: { copy: ReturnType<typeof t> }) { return <section className="methodology-section" id="methodology" aria-labelledby="method-title"><div className="section-heading"><div><p className="section-kicker">07 / METHOD</p><h2 id="method-title">{copy.methodology}</h2></div><p className="section-context">The experiment is designed to be reproducible, bounded, and explicit about uncertainty.</p></div><div className="method-columns"><div><h3>What is measured</h3><p>{copy.methodText}</p><ul><li>Search-result metadata, not republished page bodies</li><li>Top 10 primary score and Top 20 supporting score</li><li>Direct HTTP checks for URL survival, movement, and replacement candidates</li></ul></div><div><h3>What is not claimed</h3><p>{copy.persistenceText}</p><ul><li>No AI-generation classification</li><li>No prediction of the internet’s lifespan</li><li>No inference about the whole web from this panel</li></ul></div></div></section> }

function AuditStats({ audit, copy }: { audit: OfficialAudit; copy: ReturnType<typeof t> }) {
  const stats = [
    [copy.queriesObserved, audit.queriesObserved ?? audit.queries.length],
    [copy.resultsCollected, audit.resultsCollected ?? audit.queries.reduce((sum, item) => sum + item.returned_count, 0)],
    [copy.uniqueUrls, audit.uniqueNormalizedUrls ?? '—'],
    [copy.duplicateUrls, audit.duplicateNormalizedUrls ?? '—'],
    [copy.top20Availability, audit.top20Available ?? audit.queries.filter((item) => item.returned_count >= 11).length],
  ]
  return <div className="audit-stats">{stats.map(([label, value]) => <div key={String(label)}><span>{label}</span><strong>{formatCount(value as number | null)}</strong></div>)}<div><span>{copy.complete} / {copy.partialStatus} / {copy.failed}</span><strong>{audit.statusCounts?.success ?? audit.queries.filter((item) => item.status === 'success').length} / {audit.statusCounts?.partial ?? audit.queries.filter((item) => item.status === 'partial').length} / {audit.statusCounts?.failure ?? audit.queries.filter((item) => item.status === 'failure').length}</strong></div></div>
}

function AuditSummary({ audit, copy, locale }: { audit: OfficialAudit; copy: ReturnType<typeof t>; locale: Locale }) {
  const representative = audit.queries.slice(0, 5)
  const partial = audit.queries.find((item) => item.status === 'partial')
  return <section className="audit-summary-section" id="audit-summary" aria-labelledby="audit-summary-title"><div className="section-heading"><div><p className="section-kicker">08 / AUDIT SUMMARY</p><h2 id="audit-summary-title">{copy.auditTitle}</h2></div><a className="text-link" href={auditHref(locale)}>{copy.viewAudit} <Arrow /></a></div>{!audit.hasObservation ? <div className="history-empty compact"><SearchIcon /><strong>{copy.notEnough}</strong><p>{copy.monitorEmpty}</p></div> : <><AuditStats audit={audit} copy={copy} />{partial && <p className="audit-explanation"><InfoIcon />{copy.partialExplanation(partial.returned_count, partial.requested_count)}</p>}<div className="representative-list"><div className="representative-heading"><span>{copy.representative}</span><span>{copy.top10} / {copy.top20}</span></div>{representative.map((item) => <div className="representative-row" key={item.query}><div><b>{item.domain}</b><strong>{item.query}</strong></div><span>{item.returned_count}/{item.requested_count}</span><span>{item.score ?? '—'} / {top20Score(item) ?? copy.top20Unavailable}</span></div>)}</div></>}</section>
}

function AuditRow({ item, copy }: { item: OfficialQueryAudit; copy: ReturnType<typeof t> }) {
  const availableTop20 = top20Score(item)
  return <><tr><th><span>{item.domain}</span>{item.query}</th><td>{item.returned_count}/{item.requested_count}<small>{statusLabel(item.status, copy)}</small></td><td>{item.score ?? '—'}</td><td className={availableTop20 === null ? 'unavailable-cell' : ''}>{availableTop20 ?? copy.top20Unavailable}</td><td>{item.missingMetrics.join(', ') || '—'}</td></tr></>
}

function AuditPage({ audit, copy, locale }: { audit: OfficialAudit; copy: ReturnType<typeof t>; locale: Locale }) {
  const [category, setCategory] = useState('')
  const [status, setStatus] = useState('')
  const [query, setQuery] = useState('')
  const categories = [...new Set(audit.queries.map((item) => item.domain))]
  const filtered = useMemo(() => audit.queries.filter((item) => (!category || item.domain === category) && (!status || item.status === status) && (!query || item.query.toLowerCase().includes(query.toLowerCase()))), [audit.queries, category, status, query])
  const partial = audit.queries.find((item) => item.status === 'partial')
  return <main className="audit-page" id="top"><section className="audit-hero"><a className="back-link" href={homeHref(locale)}><Arrow /> {copy.auditBack}</a><p className="section-kicker">PUBLIC DATA / EN-US-CORE-V1</p><h1>{copy.auditTitle}</h1><p>{copy.auditIntro}</p><span>{audit.observedAt ? formatDate(audit.observedAt, locale) : copy.notEnough}</span></section>{audit.hasObservation && <section className="audit-page-body"><AuditStats audit={audit} copy={copy} />{partial && <p className="audit-explanation"><InfoIcon />{copy.partialExplanation(partial.returned_count, partial.requested_count)}</p>}<div className="audit-filters" aria-label={copy.auditTitle}><label>{copy.allCategories}<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">{copy.allCategories}</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label>{copy.allStatuses}<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">{copy.allStatuses}</option><option value="success">{copy.complete}</option><option value="partial">{copy.partialStatus}</option><option value="failure">{copy.failed}</option></select></label><label className="audit-query-filter">{copy.filterQuery}<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={copy.filterQuery} /></label></div><p className="filter-result-count">{filtered.length} / {audit.queries.length}</p><div className="audit-table-wrap audit-desktop"><table className="audit-table"><thead><tr><th>Query</th><th>{copy.results}</th><th>{copy.top10}</th><th>{copy.top20}</th><th>{copy.status}</th></tr></thead><tbody>{filtered.map((item) => <AuditRow key={item.query} item={item} copy={copy} />)}</tbody></table></div><div className="audit-mobile">{filtered.map((item) => <details className="audit-card" key={item.query}><summary><span><b>{item.domain}</b>{item.query}</span><em>{statusLabel(item.status, copy)}</em></summary><div className="audit-card-body"><div><span>{copy.results}</span><strong>{item.returned_count}/{item.requested_count}</strong></div><div><span>{copy.top10}</span><strong>{item.score ?? '—'}</strong></div><div><span>{copy.top20}</span><strong className={top20Score(item) === null ? 'unavailable-cell' : ''}>{top20Score(item) ?? copy.top20Unavailable}</strong></div><p>{item.status === 'partial' ? copy.partialExplanation(item.returned_count, item.requested_count) : item.query_rationale ?? item.missingMetrics.join(', ')}</p></div></details>)}</div></section>}{!audit.hasObservation && <section className="audit-page-empty"><SearchIcon /><h2>{copy.notEnough}</h2><p>{copy.monitorEmpty}</p></section>}</main>
}

function OverviewPage({ official, audit, copy, locale }: { official: OfficialOverview; audit: OfficialAudit; copy: ReturnType<typeof t>; locale: Locale }) {
  return <main id="top"><section className="hero-section" aria-labelledby="hero-title"><div className="hero-copy"><p className="section-kicker">PUBLIC DATA EXPERIMENT / EN-US-CORE-V1</p><h1 id="hero-title">{copy.hero}</h1><p className="hero-description">{copy.description}</p><p className="hero-context">{copy.context}</p></div><div className="hero-signal" aria-hidden="true"><span /><span /><span /><span /><span /><span /><span /><span /></div></section><ScoreOverview official={official} copy={copy} />{official.monitor.hasHistory ? <Monitor official={official} copy={copy} /> : <BaselineEstablished copy={copy} />}<Categories official={official} copy={copy} />{official.monitor.hasHistory && <Timeline official={official} copy={copy} />}{official.monitor.hasHistory && <Events official={official} copy={copy} />}<LiveSearch locale={locale} copy={copy} /><Methodology copy={copy} /><AuditSummary audit={audit} copy={copy} locale={locale} /></main>
}

function App() {
  const path = window.location.pathname
  const locale = useMemo(() => localeFromPath(path), [path])
  const auditPage = isAuditPath(path)
  const [official, setOfficial] = useState<OfficialOverview>(emptyOfficialOverview)
  const [audit, setAudit] = useState<OfficialAudit>({ hasObservation: false, queries: [] })
  const copy = t(locale ?? 'en')
  useEffect(() => { if (!locale || !isKnownPath(path)) return; localStorage.setItem('entropy-locale', locale); document.documentElement.lang = locale; const pageUrl = `${window.location.origin}${auditPage ? auditHref(locale) : homeHref(locale)}`; const title = auditPage ? `INTERNET ENTROPY — ${copy.auditTitle}` : locale === 'en' ? 'INTERNET ENTROPY — Information keeps growing.' : `INTERNET ENTROPY — ${copy.hero}`; document.title = title; const setMeta = (selector: string, attrs: Record<string, string>) => { const element = document.querySelector(selector) ?? document.head.appendChild(Object.assign(document.createElement('meta'), attrs)); for (const [key, value] of Object.entries(attrs)) element.setAttribute(key, value) }; setMeta('meta[name="description"]', { name: 'description', content: auditPage ? copy.auditIntro : copy.description }); setMeta('meta[property="og:title"]', { property: 'og:title', content: title }); setMeta('meta[property="og:description"]', { property: 'og:description', content: auditPage ? copy.auditIntro : copy.description }); setMeta('meta[property="og:url"]', { property: 'og:url', content: pageUrl }); setMeta('meta[name="twitter:title"]', { name: 'twitter:title', content: title }); setMeta('meta[name="twitter:description"]', { name: 'twitter:description', content: auditPage ? copy.auditIntro : copy.description }); const canonical = document.querySelector('link[rel="canonical"]') ?? document.head.appendChild(Object.assign(document.createElement('link'), { rel: 'canonical' })); canonical.setAttribute('href', pageUrl); for (const item of locales) { let link = document.querySelector(`link[hreflang="${item.id}"]`) as HTMLLinkElement | null; if (!link) { link = document.createElement('link'); link.rel = 'alternate'; link.hreflang = item.id; document.head.appendChild(link) }; link.href = `${window.location.origin}${auditPage ? auditHref(item.id) : item.href}` }; let xDefault = document.querySelector('link[hreflang="x-default"]') as HTMLLinkElement | null; if (!xDefault) { xDefault = document.createElement('link'); xDefault.rel = 'alternate'; document.head.appendChild(xDefault) }; xDefault.href = `${window.location.origin}${auditPage ? auditHref('en') : '/'}`; }, [auditPage, copy, locale, path])
  useEffect(() => { if (!locale || !isKnownPath(path)) return; Promise.all([fetch(`/api/observations?panel=en-us-core-v1&lang=${locale}`).then((response) => response.ok ? response.json() as Promise<OfficialOverview> : null), fetch('/api/observations/latest?panel=en-us-core-v1').then((response) => response.ok ? response.json() as Promise<OfficialAudit> : null)]).then(([overview, latest]) => { if (overview) setOfficial(overview); if (latest) setAudit(latest) }).catch(() => undefined) }, [locale, path])
  if (!locale) return <div className="not-found"><h1>{copy.notFound}</h1><a href="/">{copy.backHome}</a></div>
  return <div className="app-shell"><header className="site-header"><a href={homeHref(locale)} className="brand">INTERNET <span>ENTROPY</span></a><nav aria-label="Primary navigation"><a href={`${homeHref(locale)}#overview`}>{copy.navOverview}</a><a href={`${homeHref(locale)}#monitor`}>{copy.navMonitor}</a><a href={`${homeHref(locale)}#timeline`}>{copy.navTimeline}</a><a href={`${homeHref(locale)}#categories`}>{copy.navCategories}</a><a href={`${homeHref(locale)}#methodology`}>{copy.navMethod}</a><a className="nav-action" href={`${homeHref(locale)}#live`}><span>↗</span>{copy.navLive}</a></nav><div className="language-switcher" aria-label={copy.language}>{locales.map((item) => <a className={item.id === locale ? 'selected' : ''} href={auditPage ? auditHref(item.id) : item.href} key={item.id}>{item.label}</a>)}</div></header>{auditPage ? <AuditPage audit={audit} copy={copy} locale={locale} /> : <OverviewPage official={official} audit={audit} copy={copy} locale={locale} />}<footer className="site-footer"><div><a href={homeHref(locale)} className="brand">INTERNET <span>ENTROPY</span></a><p>{copy.footer}</p></div><div className="footer-links">{locales.map((item) => <a href={auditPage ? auditHref(item.id) : item.href} key={item.id}>{item.label}</a>)}<a href={auditHref(locale)}>{copy.auditTitle}</a><a href="https://github.com/flan2525/internet-entropy" rel="noreferrer">GitHub</a></div><div className="footer-note">{copy.context}<br />The experiment does not predict the lifespan of the internet.</div></footer></div>
}

export default App
