import { FormEvent, useEffect, useMemo, useState } from 'react'
import { emptyExperiment, emptyOfficialOverview } from './lib/sample'
import { isKnownPath, localeFromPath, locales, t } from './lib/i18n'
import type { ExperimentResult, Locale, OfficialAudit, OfficialOverview } from './lib/types'

const formatDate = (value: string | null | undefined, locale: Locale) => value ? new Intl.DateTimeFormat(locale === 'zh-CN' ? 'zh-CN' : locale, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'
const formatCount = (value: number | null | undefined) => value === null || value === undefined ? '—' : value.toLocaleString()
const statusLabel = (status: string, copy: ReturnType<typeof t>) => ({ dropped_from_top_10: copy.dropped10, dropped_from_top_20: copy.dropped20, moved: copy.moved, redirected: copy.moved, disappeared: copy.disappeared, replaced_candidate: copy.replacement, temporarily_unavailable: copy.temporary, persistent_unavailable: copy.temporary, blocked: copy.unverifiable, unverifiable: copy.unverifiable }[status] ?? status.replaceAll('_', ' '))

function Arrow() { return <svg className="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15M13 6l6 6-6 6" /></svg> }
function SearchIcon() { return <svg className="icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.8" cy="10.8" r="6.5" /><path d="m16 16 5 5" /></svg> }
function ClockIcon() { return <svg className="icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8.5" /><path d="M12 7v5l3 2" /></svg> }
function InfoIcon() { return <svg className="icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9" /><path d="M12 10v6M12 7.5h.01" /></svg> }

function ScoreOverview({ official, copy }: { official: OfficialOverview; copy: ReturnType<typeof t> }) {
  const items = [
    { label: copy.score, value: official.score, note: official.hasObservation ? copy.provisional : copy.noObservation, className: 'score-primary', isScore: true },
    { label: 'Top 20 supporting score', value: official.top20Score, note: official.hasObservation ? 'Search-result fringe' : '—', className: 'score-supporting', isScore: true },
    { label: 'Observation runs', value: official.completedRuns, note: official.hasObservation ? 'Public English panel' : '—', className: 'score-supporting', isScore: false },
    { label: 'Tracked pages', value: official.analyzedPages, note: official.hasObservation ? `Top ${official.resultCount}` : '—', className: 'score-supporting', isScore: false },
  ]
  return <section className="overview-section" id="overview" aria-labelledby="overview-title"><div className="section-heading"><div><p className="section-kicker">01 / OBSERVATION OVERVIEW</p><h2 id="overview-title">Current observation</h2></div><p className="section-context">{copy.context}<br /><span>{official.panelId} · {official.methodologyVersion}</span></p></div><div className="score-grid">{items.map((item) => <article className={`score-card ${item.className}`} key={item.label}><span>{item.label}</span><strong>{item.value === null || item.value === undefined ? '—' : item.value}{item.value !== null && item.value !== undefined && item.isScore && <small>/100</small>}</strong><em>{item.note}</em></article>)}</div><div className="score-footnote"><span>{official.isBaseline ? `● ${copy.baseline}` : copy.provisional}</span><span>{official.hasObservation ? `${official.metricCoverage.available} of ${official.metricCoverage.total} indicators available · ${copy.persistenceLater}` : copy.noObservation}</span></div></section>
}

function Monitor({ official, copy }: { official: OfficialOverview; copy: ReturnType<typeof t> }) {
  const monitor = official.monitor
  const cards = [{ label: copy.tracking, value: monitor.trackingUrls }, { label: copy.stillRanked, value: monitor.stillRanked }, { label: copy.dropped10, value: monitor.droppedFromTop10 }, { label: copy.dropped20, value: monitor.droppedFromTop20 }, { label: copy.aliveDropped, value: monitor.aliveButNoLongerRanked }, { label: copy.moved, value: monitor.redirectedOrMoved }, { label: copy.temporary, value: monitor.temporarilyUnavailable }, { label: copy.disappeared, value: monitor.confirmedDisappeared }, { label: copy.replacement, value: monitor.replacementCandidates }, { label: copy.unverifiable, value: monitor.unverifiable }]
  return <section className="monitor-section" id="monitor" aria-labelledby="monitor-title"><div className="section-heading"><div><p className="section-kicker">02 / DISAPPEARANCE MONITOR</p><h2 id="monitor-title">{copy.monitorTitle}</h2></div><p className="section-context">{copy.monitorIntro}</p></div>{!monitor.hasHistory ? <div className="history-empty"><SearchIcon /><strong>{copy.notEnough}</strong><p>{copy.monitorEmpty}</p></div> : <><div className="monitor-grid">{cards.map((card) => <div className="monitor-stat" key={card.label}><span>{card.label}</span><strong>{formatCount(card.value)}</strong></div>)}</div><div className="monitor-split"><div><div className="split-heading"><span>A · SEARCH-RESULT DEPARTURE</span><small>{copy.top10} / {copy.top20}</small></div><p>Pages that remain on the web but leave the observed search results.</p><div className="split-bars"><div><span>{copy.top10}</span><i style={{ width: `${Math.min(100, (monitor.droppedFromTop10 ?? 0) / Math.max(1, monitor.trackingUrls ?? 1) * 100)}%` }} /></div><div><span>{copy.top20}</span><i className="amber" style={{ width: `${Math.min(100, (monitor.droppedFromTop20 ?? 0) / Math.max(1, monitor.trackingUrls ?? 1) * 100)}%` }} /></div></div></div><div><div className="split-heading"><span>B · WEB-PAGE STATUS</span><small>HTTP evidence</small></div><p>Pages checked directly, separately from search ranking.</p><div className="status-dots"><span><i className="dot teal" />{copy.moved}</span><span><i className="dot amber" />{copy.temporary}</span><span><i className="dot red" />{copy.disappeared}</span></div></div></div></>}</section>
}

function Timeline({ official, copy }: { official: OfficialOverview; copy: ReturnType<typeof t> }) {
  return <section className="timeline-section" id="timeline" aria-labelledby="timeline-title"><div className="section-heading"><div><p className="section-kicker">03 / HISTORY</p><h2 id="timeline-title">{copy.timeline}</h2></div><p className="section-context">Counts are published only after an official run completes.</p></div>{!official.monitor.hasHistory ? <div className="timeline-empty"><span>BASELINE</span><strong>{copy.notEnough}</strong><small>Timeline will populate after the next official observation.</small></div> : <div className="timeline-track">{official.monitor.timeline.map((item) => <div className="timeline-node" key={item.runId}><i /><strong>{formatDate(item.observedAt, 'en').split(',')[0]}</strong><span>{item.searchDepartures ?? '—'} departures</span></div>)}</div>}</section>
}

function Categories({ official, copy }: { official: OfficialOverview; copy: ReturnType<typeof t> }) {
  return <section className="category-section" id="categories" aria-labelledby="category-title"><div className="section-heading"><div><p className="section-kicker">04 / PANEL COMPARISON</p><h2 id="category-title">{copy.category}</h2></div><p className="section-context">The primary score uses Top 10. Top 20 is a supporting view.</p></div><div className="category-table-wrap"><table className="category-table"><thead><tr><th>Category</th><th>{copy.top10}</th><th>{copy.top20}</th><th>Pages</th></tr></thead><tbody>{official.domains.map((item) => <tr key={item.name}><th>{item.name}</th><td>{item.score ?? '—'}{item.score !== null && <small>/100</small>}</td><td>{item.top20Score ?? '—'}{item.top20Score !== null && <small>/100</small>}</td><td>{formatCount(item.pages)}</td></tr>)}</tbody></table></div></section>
}

function Events({ official, copy }: { official: OfficialOverview; copy: ReturnType<typeof t> }) {
  return <section className="events-section" id="events" aria-labelledby="events-title"><div className="section-heading"><div><p className="section-kicker">05 / EVENT LOG</p><h2 id="events-title">{copy.events}</h2></div><p className="section-context">Search departure is not web disappearance. Each event keeps its evidence.</p></div>{!official.monitor.hasHistory || !official.monitor.events.length ? <div className="events-empty"><ClockIcon /><strong>{official.monitor.hasHistory ? copy.noEvents : copy.notEnough}</strong><p>{official.monitor.hasHistory ? 'Events will appear when tracked URLs change state.' : copy.monitorEmpty}</p></div> : <div className="event-list">{official.monitor.events.map((event) => <article className="event-row" key={event.id}><div className="event-icon"><ClockIcon /></div><div className="event-main"><strong>{event.title}</strong><span>{event.domain} · {event.query}</span><p>{event.evidence}</p></div><div className="event-meta"><b>{statusLabel(event.search_status, copy)}</b><span>{statusLabel(event.web_status, copy)}</span><small>{formatDate(event.updated_at ?? event.last_seen_at, 'en')}</small></div></article>)}</div>}</section>
}

function LiveSearch({ locale, copy }: { locale: Locale; copy: ReturnType<typeof t> }) {
  const [query, setQuery] = useState('')
  const [result, setResult] = useState<ExperimentResult>(emptyExperiment())
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [shared, setShared] = useState(false)
  const run = async (event: FormEvent) => { event.preventDefault(); const normalized = query.trim().replace(/\s+/g, ' '); if (normalized.length < 2 || normalized.length > 80 || /https?:\/\//i.test(normalized) || /@/.test(normalized)) { setError(copy.error); return }; setError(''); setBusy(true); try { const response = await fetch(`/api/live?q=${encodeURIComponent(normalized)}&lang=${encodeURIComponent(locale)}`, { headers: { Accept: 'application/json' } }); const payload = await response.json(); if (!response.ok && !payload.result) throw new Error('unavailable'); setResult(payload.result ?? payload); if (!response.ok) setError(payload.error ?? copy.noMeasured) } catch { setResult(emptyExperiment(normalized)); setError(copy.noMeasured) } finally { setBusy(false) } }
  const share = async () => { const text = result.totalResults ? `${copy.top10Sentence(result.highSimilarityPairs, Math.min(10, result.totalResults))} ${copy.lineageSentence(result.lineageCount)} ${copy.primarySentence(result.primarySourceReach)}` : copy.noMeasured; try { await navigator.clipboard.writeText(`${text}\n${window.location.href}#live`); await fetch('/api/live/usage', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ event: 'share', lang: locale }) }); setShared(true) } catch { setShared(false) } }
  return <section className="live-section" id="live" aria-labelledby="live-title"><div className="section-heading"><div><p className="section-kicker">06 / ONE-QUERY LIVE SEARCH</p><h2 id="live-title">{copy.liveTitle}</h2></div><p className="section-context">{copy.liveIntro}<br />{copy.liveNote}</p></div><form className="live-form" onSubmit={run}><label htmlFor="live-query">{copy.searchPlaceholder}</label><div><input id="live-query" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={copy.searchPlaceholder} maxLength={80} /><button type="submit" disabled={busy}>{busy ? copy.searching : copy.search} <Arrow /></button></div>{error && <p className="form-error" role="alert"><InfoIcon />{error}</p>}</form>{result.totalResults > 0 && <div className="live-result"><div className="live-summary"><p>{copy.top10Sentence(result.highSimilarityPairs, Math.min(10, result.totalResults))}</p><p>{copy.lineageSentence(result.lineageCount)}</p><p>{copy.primarySentence(result.primarySourceReach)}</p></div><div className="live-metrics"><div><span>{copy.results}</span><strong>{result.totalResults}</strong></div><div><span>{copy.lineages}</span><strong>{result.lineageCount}</strong></div><div><span>{copy.primary}</span><strong>{result.primarySourceReach}</strong></div><div><span>{copy.unavailable}</span><strong>{result.unavailableCount}</strong></div></div><div className="lineage-bars">{result.clusters.map((cluster) => <div key={cluster.id}><span>{cluster.label}</span><i style={{ width: `${cluster.resultCount / Math.max(1, result.totalResults) * 100}%`, background: cluster.color }} /><small>{cluster.resultCount}</small></div>)}</div><button className="share-button" type="button" onClick={share}>{shared ? copy.shared : copy.share} <Arrow /></button></div>}</section>
}

function Methodology({ copy }: { copy: ReturnType<typeof t> }) { return <section className="methodology-section" id="methodology" aria-labelledby="method-title"><div className="section-heading"><div><p className="section-kicker">07 / METHOD</p><h2 id="method-title">{copy.methodology}</h2></div><p className="section-context">The experiment is designed to be reproducible, bounded, and explicit about uncertainty.</p></div><div className="method-columns"><div><h3>What is measured</h3><p>{copy.methodText}</p><ul><li>Search-result metadata, not republished page bodies</li><li>Top 10 primary score and Top 20 supporting score</li><li>Direct HTTP checks for URL survival, movement, and replacement candidates</li></ul></div><div><h3>What is not claimed</h3><p>{copy.persistenceText}</p><ul><li>No AI-generation classification</li><li>No prediction of the internet’s lifespan</li><li>No inference about the whole web from this panel</li></ul></div></div></section> }

function App() {
  const locale = useMemo(() => localeFromPath(window.location.pathname), [])
  const [official, setOfficial] = useState<OfficialOverview>(emptyOfficialOverview)
  const [audit, setAudit] = useState<OfficialAudit>({ hasObservation: false, queries: [] })
  const copy = t(locale ?? 'en')
  useEffect(() => { if (!locale || !isKnownPath(window.location.pathname)) return; localStorage.setItem('entropy-locale', locale); document.documentElement.lang = locale; const pageUrl = `${window.location.origin}${locale === 'en' ? '/' : `/${locale === 'zh-CN' ? 'zh' : locale}/`}`; const title = locale === 'en' ? 'INTERNET ENTROPY — Information keeps growing.' : `INTERNET ENTROPY — ${copy.hero}`; document.title = title; const setMeta = (selector: string, attrs: Record<string, string>) => { const element = document.querySelector(selector) ?? document.head.appendChild(Object.assign(document.createElement('meta'), attrs)); for (const [key, value] of Object.entries(attrs)) element.setAttribute(key, value) }; setMeta('meta[name="description"]', { name: 'description', content: copy.description }); setMeta('meta[property="og:title"]', { property: 'og:title', content: title }); setMeta('meta[property="og:description"]', { property: 'og:description', content: copy.description }); setMeta('meta[property="og:url"]', { property: 'og:url', content: pageUrl }); setMeta('meta[name="twitter:title"]', { name: 'twitter:title', content: title }); setMeta('meta[name="twitter:description"]', { name: 'twitter:description', content: copy.description }); const canonical = document.querySelector('link[rel="canonical"]') ?? document.head.appendChild(Object.assign(document.createElement('link'), { rel: 'canonical' })); canonical.setAttribute('href', pageUrl); for (const item of locales) { let link = document.querySelector(`link[hreflang="${item.id}"]`) as HTMLLinkElement | null; if (!link) { link = document.createElement('link'); link.rel = 'alternate'; link.hreflang = item.id; document.head.appendChild(link) }; link.href = `${window.location.origin}${item.href}` }; let xDefault = document.querySelector('link[hreflang="x-default"]') as HTMLLinkElement | null; if (!xDefault) { xDefault = document.createElement('link'); xDefault.rel = 'alternate'; xDefault.hreflang = 'x-default'; document.head.appendChild(xDefault) }; xDefault.href = `${window.location.origin}/`; }, [copy, locale])
  useEffect(() => { if (!locale) return; Promise.all([fetch(`/api/observations?panel=en-us-core-v1&lang=${locale}`).then((response) => response.ok ? response.json() as Promise<OfficialOverview> : null), fetch('/api/observations/latest?panel=en-us-core-v1').then((response) => response.ok ? response.json() as Promise<OfficialAudit> : null)]).then(([overview, latest]) => { if (overview) setOfficial(overview); if (latest) setAudit(latest) }).catch(() => undefined) }, [locale])
  if (!locale) return <div className="not-found"><h1>{copy.notFound}</h1><a href="/">{copy.backHome}</a></div>
  return <div className="app-shell"><header className="site-header"><a href={locale === 'en' ? '/' : `/${locale}/`} className="brand">INTERNET <span>ENTROPY</span></a><nav aria-label="Primary navigation"><a href="#overview">{copy.navOverview}</a><a href="#monitor">{copy.navMonitor}</a><a href="#timeline">{copy.navTimeline}</a><a href="#categories">{copy.navCategories}</a><a href="#methodology">{copy.navMethod}</a><a className="nav-action" href="#live"><span>↗</span>{copy.navLive}</a></nav><div className="language-switcher" aria-label={copy.language}>{locales.map((item) => <a className={item.id === locale ? 'selected' : ''} href={item.href} key={item.id}>{item.label}</a>)}</div></header><main id="top"><section className="hero-section" aria-labelledby="hero-title"><div className="hero-copy"><p className="section-kicker">PUBLIC DATA EXPERIMENT / EN-US-CORE-V1</p><h1 id="hero-title">{copy.hero}</h1><p className="hero-description">{copy.description}</p><p className="hero-context">{copy.context}</p></div><div className="hero-signal" aria-hidden="true"><span /><span /><span /><span /><span /><span /><span /><span /></div></section><ScoreOverview official={official} copy={copy} /><Monitor official={official} copy={copy} /><Timeline official={official} copy={copy} /><Categories official={official} copy={copy} /><Events official={official} copy={copy} /><LiveSearch locale={locale} copy={copy} /><Methodology copy={copy} /><section className="audit-section" id="audit" aria-labelledby="audit-title"><div className="section-heading"><div><p className="section-kicker">08 / QUERY AUDIT</p><h2 id="audit-title">Top 10 / Top 20 audit</h2></div><p className="section-context">{audit.hasObservation ? `${audit.queries.length} fixed English queries · ${audit.analyzedPages ?? 0} pages` : copy.notEnough}</p></div>{audit.hasObservation ? <div className="audit-table-wrap"><table className="audit-table"><thead><tr><th>Query</th><th>Returned</th><th>Top 10</th><th>Top 20</th><th>Missing</th></tr></thead><tbody>{audit.queries.map((item) => <tr key={item.query}><th><span>{item.domain}</span>{item.query}</th><td>{item.returned_count}/{item.requested_count}<small>{item.status}</small></td><td>{item.score ?? '—'}</td><td>{item.top20_score ?? '—'}</td><td>{item.missingMetrics.join(', ') || '—'}</td></tr>)}</tbody></table></div> : <div className="history-empty compact"><SearchIcon /><strong>{copy.notEnough}</strong><p>{copy.monitorEmpty}</p></div>}</section></main><footer className="site-footer"><div><a href="#top" className="brand">INTERNET <span>ENTROPY</span></a><p>{copy.footer}</p></div><div className="footer-links">{locales.map((item) => <a href={item.href} key={item.id}>{item.label}</a>)}<a href="#methodology">{copy.navMethod}</a><a href="https://github.com/flan2525/internet-entropy" rel="noreferrer">GitHub</a></div><div className="footer-note">{copy.context}<br />The experiment does not predict the lifespan of the internet.</div></footer></div>
}

export default App
